---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-dev
spec:
  selector:
    matchLabels:
      app: pyapp
  replicas: 1
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: pyapp
        image: ecitanand/pyapp:1.1
        env:
        - name: FLASK_APP
          value: "project/__init__.py"
        - name: FLASK_DEBUG
          value: "1"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-port
spec:
  type: NodePort      
  selector:
    app: pyapp
  ports:
    - nodePort: 30001
      port: 8081
      targetPort: 5000
